#!/bin/bash -e

# Add logstash as command if needed
if [ "${1:0:1}" = '-' ]; then
  set -- logstash "$@"
fi

# Replace all set environment variables from in the current shell session.
# The environment variables present in the file but are unset will remain untouched.
# Replaced pattern is: ${<ENV_VAR>}
function substenv {
  local in_file="$1"
  local out_file="$2"
  local temp_file="$(mktemp -t substenv.XXXX)"
  cat "${in_file}" > ${temp_file}
  compgen -v | while read var ; do
    sed -i "s/\${$var}/$(echo ${!var} | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e 's/&/\\\&/g')/g" "${temp_file}"
  done
  cat "${temp_file}" > "${out_file}" && rm -f "${temp_file}"
}

# Map user to current UID/GID
export USER_ID="$(id -u)"
export GROUP_ID="$(id -g)"
substenv ${HOME}/passwd.in /tmp/passwd
export NSS_WRAPPER_PASSWD=/tmp/passwd
export NSS_WRAPPER_GROUP=/etc/group
export LD_PRELOAD=/usr/lib64/libnss_wrapper.so

# execute all init scripts
files=$(shopt -s nullglob dotglob; echo "${INIT_DIR}"/*)
for f in ${files} ; do
  echo "Initialize environment from $f"
  set -o allexport
  source "${f}"
  set +o allexport
done

# As argument is not related to elasticsearch,
# then assume that user wants to run his own process,
# for example a `bash` shell to explore this image
exec "$@"
